### ISSUE TITLE
Error executing ERC721 token operation with invalid token ID in LitJsSdk

### ISSUE THREAD

**Issue by bradleycm** [LIT-Protocol/js-sdk#10]
The error message indicates that the code is encountering an execution revert when attempting to execute an ERC721 token operation with an invalid token ID.

From the code provided, it seems that it is using the LitJsSdk to connect to a Lit node and execute a script that attempts to sign an ECDSA signature using the Lit.Actions.signEcdsa() method. The parameters passed to this method include the toSign, publicKey, and sigName values, which are passed in from the jsParams object in the litNodeClient.executeJs() method.

To reproduce the issue, create a Next.js app with `npx create-next-app@latest debug && cd debug` utility, then install the lit-js-sdk package with `npm install lit-js-sdk` then add the code provided attached to a button.

 - `@lit-protocol/lit-node-client` version: "^2.0.40" 
 - Network: "serrano"
 - Node version: v19.1.0
 - Framework: NextJS 
 - Build tool: Webpack

Also note I have to use `ts-ignore` as typescript throws error that `checkAndSignAuthMessage` and `LitNodeClient` do not exist on `LitJsSdk`.

Executed:
```ts
import LitJsSdk from "lit-js-sdk";

async function execute() {
    // @ts-ignore
    const authSig = await LitJsSdk.checkAndSignAuthMessage({ chain: "ethereum" });
    // @ts-ignore
    const litNodeClient = new LitJsSdk.LitNodeClient({ litNetwork: "serrano" });
    await litNodeClient.connect();
    const litActionCode = `
    const go = async () => {  
      // this requests a signature share from the Lit Node
      // the signature share will be automatically returned in the HTTP response from the node
      // all the params (toSign, publicKey, sigName) are passed in from the LitJsSdk.executeJs() function
      const sigShare = await Lit.Actions.signEcdsa({ toSign, publicKey , sigName });
    };
    go();
    `;
    const signatures = await litNodeClient.executeJs({
      code: litActionCode,
      authSig,
      // all jsParams can be used anywhere in your litActionCode
      jsParams: {
        // this is the string "Hello World" for testing
        toSign: [72, 101, 108, 108, 111, 32, 87, 111, 114, 108, 100],
        publicKey:
            "0x02e5896d70c1bc4b4844458748fe0f936c7919d7968341e391fb6d82c258192e64",
        sigName: "sig1",
      },
    });
    console.log("signatures: ", signatures);
}
```

Error:
```json
{
"message":"Error executing JS: Error: (code: 3, message: execution reverted: ERC721: invalid token ID, 
data: Some(String(\"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000
00000000000000000000000000000000000000000000000000000184552433732313a20696e76616c696420746f6b656e204944
0000000000000000\")))\n    at async go (<user_provided_script>:6:24)",
"errorCode":"js_execution_error"
}
```

**Screenshots**
<img width="987" alt="Screen Shot 2023-01-14 at 8 51 00 PM" src="https://user-images.githubusercontent.com/17681450/212510565-8b50bae7-6011-4f65-b187-cc043932a310.png">
<img width="987" alt="Screen Shot 2023-01-14 at 8 51 19 PM" src="https://user-images.githubusercontent.com/17681450/212510680-2fb04303-5090-4a7d-9d60-05b57fea54cd.png">
<img width="968" alt="Screen Shot 2023-01-14 at 8 51 38 PM" src="https://user-images.githubusercontent.com/17681450/212510793-484fadee-3e3d-4dc2-b4b4-34ce6e4b38cd.png">

**Comment by glitch003** [comment]
where did you get the value publicKey?  it looks too short and should start with 0x04. 

it should be a publicKey of a PKP which you can mint on the explorer at explorer.litprotocol.com

**Comment by bradleycm** [comment]
> where did you get the value publicKey? it looks too short and should start with 0x04.
> 
> it should be a publicKey of a PKP which you can mint on the explorer at explorer.litprotocol.com

I am following these docs: https://developer.litprotocol.com/SDK/Explanation/LitActions/helloWorld

I do not see mention of where this public key gets generated from

**Comment by bradleycm** [comment]
Closing this as that was the issue, thanks @glitch003
