### ISSUE TITLE
Some tests failed

### ISSUE THREAD

**Issue by johnnynanjiang** [LIT-Protocol/js-sdk#120]
1. `yarn build` failed

```
$ yarn build
yarn run v1.22.19
$ yarn build:packages
$ yarn tools check --no-empty-directories=true && yarn tools fixTsConfig && yarn reset && yarn tools --build --packages && yarn tools --postBuild && yarn tools --setup-local-dev && yarn postBuild:mapDepsToDist && yarn gen:readme && yarn build:verify
$ yarn node ./tools/scripts/tools.mjs check --no-empty-directories=true
$ yarn node ./tools/scripts/tools.mjs fixTsConfig
error Command failed.
Exit code: 13
Command: /Users/???/.nvm/versions/node/v16.10.0/bin/node
Arguments: ./tools/scripts/tools.mjs fixTsConfig
Directory: /Users/???/code/js-sdk
Output:

info Visit https://yarnpkg.com/en/docs/cli/node for documentation about this command.
error Command failed with exit code 13.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 13.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 13.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

---

2. lit-build.config.json file is missing for `yarn tools --build --packages --async`, may I have the file in order to build the project?

---

3. some tests failed with `yarn run test:unit`, mostly due to timeout.

>  NX   Ran target test for 21 projects (10m)
 
    ✔    15/21 succeeded [0 read from cache]
 
    ✖    6/21 targets failed, including the following:
         - nx run auth-browser:test
         - nx run crypto:test
         - nx run lit-auth-client:test
         - nx run contracts-sdk:test
         - nx run pkp-ethers:test
         ...and 1 more...

**Comment by hwrdtm** [comment]
cc @Ansonhkg

**Comment by johnnynanjiang** [comment]
> Which js-sdk version are you using? The --async command you saw in the readme.md is no longer in use, my apologies for any confusion caused. Also, have you tried using different node version? v18.0.0 and above

Thanks @Ansonhkg 

I was using the latest js-sdk, version 2.2.11 I think.

I switched to node version v18.0.0 (I was using v16 before), and `yarn build` worked, and `yarn test:unit` got much better results, only one failure due to timeout.
