### ISSUE TITLE
{"errorCode":"bad_input","message":"422 Unprocessable Entity (/web/encryption/retrieve)

### ISSUE THREAD

**Issue by truongcongviet** [LIT-Protocol/js-sdk#134]
I try to descrypt IPFS CID: QmWqfkRzcbDsoyawkabzHfdgrNLmy1YyvtLRne3UyPnHNQ. But I all got error 

<img width="679" alt="image" src="https://github.com/LIT-Protocol/js-sdk/assets/55937676/7b0e2bf4-fd4b-47b1-b2d2-40348f2f7558">

How can I fix it guys?

**Comment by Ansonhkg** [comment]
HI @truongcongviet , could you provide a sample app so that I could re-produce the issue and properly tackle the issue?
