### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by 0xStuart** [LIT-Protocol/js-sdk#135]
Please provide a Docker image, where you can interact with the SDK.  Dependency issues make installation difficult.

**Comment by 0xStuart** [comment]
```
# We are going to use an official Node runtime as a parent image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json into the root directory of our container
COPY package*.json ./

# Install app dependencies
RUN npm install

# Bundle app source
COPY . .

# Define the command to run our app
CMD [ "npm", "start" ]

```

I tried this stock nodejs Dockerfile, but it has issues.

**Comment by Ansonhkg** [comment]
Hey @0xStuart if you'd like to create a Docker image and feel like it could benefit other users, you're more than welcome to do so and submit a PR! At the moment we need to evaluate user base's needs & demand to justify we can maintain the Docket image.

re: I tried this stock nodejs Dockerfile, but it has issues.

Please try node version about 18.0.0, let me know if it works for you!
