### ISSUE TITLE
Getting the error message of "Invalid ipfsCid" when trying to decrypt the encrypted file uploaded to IPFS using the SDK

### ISSUE THREAD

**Issue by Eric1015** [LIT-Protocol/js-sdk#143]
**Before reporting, I have already *** 
- checked LIT Protocol [developer docs](https://developer.litprotocol.com/) and/or the [lit-js-sdk](https://lit-protocol.github.io/lit-js-sdk/api_docs_html/).
- searched for other [open issues](https://github.com/LIT-Protocol/lit-js-sdk/issues).

**Describe the bug**
I am trying to create a really simple application that will simply encrypt and upload the file to IPFS then, download by decrypting it on the application. 
As part of the encryption, I made it to specify which wallet address owner can access the file and I just use my own wallet address for that input, meaning, I should be able to decrypt it as well.

However, when I call the decrypt function after the encryption, I got the following error message in the console, and the decrypt didn't go through.

```
{
    "message": "Invalid ipfsCid",
    "errorCode": "InvalidArgumentException",
    "errorKind": "Validation"
}
```

**To Reproduce**
1. Go to this github [link](https://github.com/Eric1015/lit-encrypt-decrypt-file)
2. Download the code and run `npm install`
3. Copy and paste the contents of `.env.example` to `.env.local`
4. Create a IPFS API key on Infura and obtain the required values `INFURA_ID` and `INFURA_SECRET_KEY` and assign them in `.env.local`
5. Run the application by `npm run dev` and navigate to http://localhost:3000
6. Simply copy paste your own metamask wallet address to the first input, upload a sample file, click on "Encrypt" button, click on "Decrypt" button.
7. "Decrypt" should fail and you will be able to see the error messages in the console.

**Expected behavior**

Decryption should go through and the decrypted string should show up in the UI

**Screenshots**

![Screenshot 2023-06-13 at 11 53 20 PM](https://github.com/LIT-Protocol/js-sdk/assets/31051640/f0f4cdbb-bf4b-4cb0-8419-e684f24874f5)

**Environment:**
 - Lit SDK version (including the network (ie, "serrano") if different, and type - browser or backend) : 2.1.160
 - Node version: 18.0.0
 - Framework (React, Vue, Angular, Svelte - just Plain HTML!, etc): Next (13.4.5)
 - Specific tooling (Webpack, Vite, browserify, etc) : Nothing special

**Additional info**

Code snippet that I am facing issue with:

```
const FileEncryptDecryptForm = () => {
  const { encrypt, decrypt } = useLitFileProvider();

  const [authorizedWalletAddress, setAuthorizedWalletAddress] = useState<
    string | null
  >(null);
  const [file, setFile] = useState<File | null>(null);
  const [ipfsCid, setIpfsCid] = useState<string | null>(null);
  const [decryptedString, setDecryptedString] = useState<string | null>(null);

  const handleFileChange = async (file: File | null) => {
    setFile(file);
  };

  const handleEncryptClick = async () => {
    if (!authorizedWalletAddress) {
      alert('Please enter an authorized wallet address');
      return;
    }
    if (file && authorizedWalletAddress) {
      const ipfsCid = await encrypt(file, authorizedWalletAddress);
      console.log(ipfsCid);
      setIpfsCid(ipfsCid);
    }
  };

  const handleDecryptClick = async () => {
    if (ipfsCid) {
      // assume the ipfsCid from the encryption returned is assigned properly
      const decryptedString = await decrypt(ipfsCid);
      console.log(decryptedString);
      console.log(typeof decryptedString);
      setDecryptedString(
        typeof decryptedString === 'string'
          ? decryptedString
          : new TextDecoder().decode(decryptedString)
      );
    }
  };
};
```

**Comment by Eric1015** [comment]
I have changed the implementation a little instead by getting the source code of the `decryptFromIpfs` function and put it in my custom function, replaced the code of getting the symmetric key to the following which is the normal way to get the symmetric key, but seems like I am getting the 500 error like the following, want to know how this issue can occur:

```
      const symmetricKey = await window.litNodeClient.getEncryptionKey({
        accessControlConditions: metadata.accessControlConditions,
        toDecrypt: metadata.encryptedSymmetricKeyString,
        chain,
        authSig,
      });
```

**Comment by Eric1015** [comment]
I actually figured this out myself. I have chosen to use the `serrano` developer network for now. Although I know the contents uploaded there is subject to deletion, but for my personal project, I can tolerate this. 

I don't know if anything additional is required in the mainnet, but according to the official document, the mainnet is in alpha state and that might be the reason why it does not function well enough to support my use case at this moment.

https://developer.litprotocol.com/support/stateofnetwork/

**Comment by HelloRWA** [comment]
I also get the 500 error while trying to decrypt the content
`
POST https://node2.litgateway.com:7371/web/encryption/retrieve 500 (Internal Server Error)
`

`
curl 'https://node2.litgateway.com:7376/web/encryption/retrieve' \
  -H 'sec-ch-ua: "Not/A)Brand";v="99", "Google Chrome";v="115", "Chromium";v="115"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36' \
  -H 'X-Lit-SDK-Version: 2.2.41' \
  -H 'Content-Type: application/json' \
  -H 'Referer;' \
  -H 'X-Lit-SDK-Type: Typescript' \
  -H 'X-Request-Id: lit_62b586640d23d' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '{"accessControlConditions":[{"contractAddress":"","chain":"maticmum","standardContractType":"","method":"","parameters":[":userAddress"],"returnValueTest":{"comparator":"=","value":"0xFd191B88C97e092222475E7163353d9e83036CD4"}},{"operator":"or"},{"contractAddress":"0x8CD018727A40b5EF4c65963B09BEe7e965bdB2AA","chain":"maticmum","standardContractType":"ERC1155","method":"balanceOf","parameters":[":userAddress","35"],"returnValueTest":{"comparator":">=","value":"1"}},{"operator":"or"},{"contractAddress":"0x8CD018727A40b5EF4c65963B09BEe7e965bdB2AA","chain":"maticmum","standardContractType":"ERC1155","method":"balanceOf","parameters":[":userAddress","44"],"returnValueTest":{"comparator":">=","value":"1"}}],"toDecrypt":"8f2022198c4e00b7ba7cb40c54d6abc4564749270ebbd3ea4e26c87f3f1084154f10508dcf1601d8819434bfce3cd707706f4d9302ffd75f6b9db5d7c87b3213c07162c69694f9596ffc69983fb942f93e1eed97fe5ffceb860b6f1a09f1139086e2c2fef389161de7e5d86458053648e675435f6a0869ef35a4b52040f930340000000000000020c1996a43ad8a1017bd24d1915d47ac50d953f927fda35a45ff494475c0b452b8a52665970cc2114e12d4c7a7875cb0ad","authSig":{"sig":"0xf3a44c0ffdd23092303f05126ffaddaf7aa26f0bc46df7b3668ed5dded17421d5bf9748ecfe48c78c7bc2e878fca1edbc01bbd29f4ab59b2aaf1e303d4f0dbf11c","derivedVia":"web3.eth.personal.sign","signedMessage":"rwa-wallet.com wants you to sign in with your Ethereum account:\n0xFd191B88C97e092222475E7163353d9e83036CD4\n\nAuth with RWA-Wallet.com\n\nURI: https://rwa-wallet.com/login\nVersion: 1\nChain ID: 80001\nNonce: b7rByALyZbEEMQjcX\nIssued At: 2023-08-10T09:27:47.439Z","address":"0xFd191B88C97e092222475E7163353d9e83036CD4"},"chain":"maticmum"}' \
  --compressed
`

**Comment by scientiststwin** [comment]
I believe, Your `accessControlConditions` are incorrect, which is why you (yourself) do not have permission to access the data and will see an error.

see below example: 
```
const yourEthAddress = 'xxxxxxxxxx'
const accessControlConditions = [
  {
    contractAddress: '',
    standardContractType: '',
    chain: chain,
    method: '',
    parameters: [
      ':userAddress',
    ],
    returnValueTest: {
      comparator: '=',
      value: adminEthAddress
    }
  }
]

const ipfsCid = await litNodeClientNodejs.encryptToIpfs({
    authSig: authSigVal,
    chain: chain,
    string: stringForEncryption,
    litNodeClient: litNodeClient,
    accessControlConditions: accessControlConditions,
    infuraId: infuraId,
    infuraSecretKey: infuraSecretKey,
})

const str = await litNodeClientNodejs.decryptFromIpfs({
  authSig: authSigVal,
  ipfsCid: ipfsCid,
  litNodeClient: litNodeClient
})
console.log("[str] ", str)
```

It will be working fine :)

**Comment by Eric1015** [comment]
Hum, yeah seems like you are right.
I also made that change in my second try along with the network change, so I didn't notice it.

Thank you for the information, closing this issue.
