### ISSUE TITLE
I sighted a typographical error in the "What is Lit" section of the documentation.

### ISSUE THREAD

**Issue by ElizabethOgbee** [LIT-Protocol/js-sdk#151]
![Picture1](https://github.com/LIT-Protocol/js-sdk/assets/97669038/f8a60310-7e5f-4400-a0a8-9cbe51ff4b0c)
 Under the What is Lit Protocol Section, Its meant to be "Lit provides developers" instead of "Lit providers developers"

**Comment by Ansonhkg** [comment]
Hey @ElizabethOgbee thanks for reporting this, could you please open a PR/issue in the docs repo instead? 

- https://github.com/LIT-Protocol/docs/issues
- https://github.com/LIT-Protocol/docs/pulls

**Comment by Ansonhkg** [comment]
Hey @ElizabethOgbee thanks for reporting this, could you please open a PR/issue in the relevant repo instead? 

- https://github.com/LIT-Protocol/docs/issues
- https://github.com/LIT-Protocol/docs/pulls

**Comment by ElizabethOgbee** [comment]
Thanks. I will do that

**Comment by ElizabethOgbee** [comment]
I'ts my first time contributing to opensource so I would appreciate it if you would direct me on how to go about it. Thanks
