### ISSUE TITLE
process not defined in node_modules/util/util.js

### ISSUE THREAD

**Issue by Tejaswini-Gurumoorthy** [LIT-Protocol/js-sdk#183]
**Before reporting, I have already *** 
- checked LIT Protocol [developer docs](https://developer.litprotocol.com/) and/or the [lit-js-sdk](https://lit-protocol.github.io/lit-js-sdk/api_docs_html/).
- searched for other [open issues](https://github.com/LIT-Protocol/lit-js-sdk/issues).

**Describe the bug**
I am getting this error- util.js:109 Uncaught (in promise) ReferenceError: process is not defined
    at node_modules/util/util.js (util.js:109:1)
    at __require2 (chunk-XBCBYTQI.js?v=4f83186a:19:50)
    at bls-sdk.ts:248:11
    
**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - Lit SDK version (including the network (ie, "serrano") if different, and type - browser or backend) 
 - Node version
 - Framework (React, Vue, Angular, Svelte - just Plain HTML!, etc)
 - Specific tooling (Webpack, Vite, browserify, etc) 

**Additional info**

**Comment by Ansonhkg** [comment]
hey @Tejaswini-Gurumoorthy can you complete `To Reproduce`, `Expected behaviour`, `Screenshots` and `Environments` so that we could better debug?
