### ISSUE TITLE
Missing `saveSigningCondition` function?

### ISSUE THREAD

**Issue by anthonyra** [LIT-Protocol/js-sdk#19]
**Before reporting, I have already *** 
- checked LIT Protocol [developer docs](https://developer.litprotocol.com/) and/or the [lit-js-sdk](https://lit-protocol.github.io/lit-js-sdk/api_docs_html/).
- searched for other [open issues](https://github.com/LIT-Protocol/lit-js-sdk/issues).

**Describe the bug**

Currently I'm working with `lit-js-sdk` which I gather is v1 and wanted to check out v2 since the v1 will be deprecated sooner than later. In doing so, I can't seem to find the `saveSigningCondition` which is required for the JWT auth path.

```
1. Why do I need to call saveSigningCondition() before getSignedToken()? Shouldn’t the former just return a JWT?

The reason behind this separation is that saveSigningCondition() is a function that an admin/developer of a website will most likely call only once to set up the token-gating mechanism. The function getSignedToken() can then be called for every website visitor. You can view this as a 1-to-many relationship.
```

I do see a commit https://github.com/LIT-Protocol/js-sdk/commit/c262f044b5ea5a5e02fcf07eded5af2683d2fb54 adding it but I can't seem to find it now? (I'm still a newb at github it seems) but I'm pretty sure it's because `packages/utils/src/lib/litNodeClient.ts` doesn't exist on master anymore?

**To Reproduce**
3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**
`packages/utils/src/lib/litNodeClient.ts` might need to be added back to master?

**Screenshots**

**Environment:**
 - Lit SDK version (including the network (ie, "serrano") if different, and type - browser or backend) 
 - Node version
 - Framework (React, Vue, Angular, Svelte - just Plain HTML!, etc)
 - Specific tooling (Webpack, Vite, browserify, etc) 

**Additional info**

**Comment by glitch003** [comment]
Hey, it's here `packages/lit-node-client/src/lib/lit-node-client.ts` and not in `packages/utils`

https://github.com/LIT-Protocol/js-sdk/blob/master/packages/lit-node-client/src/lib/lit-node-client.ts#L1814

It should be working for you if you try to use it.  Are you still having issues?

**Comment by Ansonhkg** [comment]
I'm closing this thread, if not please let me know if you are still having issues
