### ISSUE TITLE
[Closing soon] Webpack Issues

### ISSUE THREAD

**Issue by anthonyra** [LIT-Protocol/js-sdk#20]
**Before reporting, I have already *** 
- checked LIT Protocol [developer docs](https://developer.litprotocol.com/) and/or the [lit-js-sdk](https://lit-protocol.github.io/lit-js-sdk/api_docs_html/).
- searched for other [open issues](https://github.com/LIT-Protocol/lit-js-sdk/issues).

**Describe the bug**

Using `create-react-app` and building with the `js-sdk` I'm running into some errors.

1. Needing to add fallbacks for `crypto` and `stream` with `crypto-browserify` and `stream-browserify`
2. Seeing a "Critical dependency: the request of a dependency is an expression" with the `ecsda-sdk`

```
To ignore, add // eslint-disable-next-line to the line before.

WARNING in ./node_modules/@lit-protocol/encryption/node_modules/@lit-protocol/crypto/node_modules/@lit-protocol/ecdsa-sdk/src/lib/ecdsa-sdk.js 312:16-55
Critical dependency: the request of a dependency is an expression
```

**To Reproduce**
1. Create new React app with `npx create-react-app my-app`
2. Update `npm start` to `"GENERATE_SOURCEMAP=false react-scripts start"` in `package.json`
3. Add the following to `node_modules/react-scripts/configs/webpack.config.js` line 305
```javascript
    resolve: {
      // This allows you to set a fallback for where webpack should look for modules.
      // We placed these paths second because we want `node_modules` to "win"
      // if there are any conflicts. This matches Node resolution mechanism.
      // https://github.com/facebook/create-react-app/issues/253
      modules: ['node_modules', paths.appNodeModules].concat(
        modules.additionalModulePaths || []
      ),
      fallback: {
        "crypto": require.resolve("crypto-browserify"),
        "stream": require.resolve("stream-browserify")
      },
```
5. Run `npm install crypto-browserify stream-browserify`
6. See
```
WARNING in ./node_modules/@lit-protocol/encryption/node_modules/@lit-protocol/crypto/node_modules/@lit-protocol/ecdsa-sdk/src/lib/ecdsa-sdk.js 312:16-55
Critical dependency: the request of a dependency is an expression
```

**Expected behavior**
Hopefully no warnings 😅

**Screenshots**

**Environment:**
```javascript
  "dependencies": {
    "@lit-protocol/lit-node-client": "^2.1.25",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "crypto-browserify": "^3.12.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "stream-browserify": "^3.0.0",
    "web-vitals": "^2.1.4"
},
```

**Additional info**

**Comment by joshLong145** [comment]
Can also confirm that these errors occur when bundling.

**Comment by AireshBhat** [comment]
@anthonyra Were you able to fix this issue?

**Comment by mattcasey** [comment]
I am seeing this issue, I was just trying to migrate from v1 to v2 in a next.js app:
```
warn  - ./node_modules/@lit-protocol/ecdsa-sdk/src/lib/ecdsa-sdk.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/@lit-protocol/ecdsa-sdk/src/lib/ecdsa-sdk.js
./node_modules/@lit-protocol/ecdsa-sdk/src/index.js
./node_modules/@lit-protocol/crypto/src/lib/crypto.js
./node_modules/@lit-protocol/crypto/src/index.js
./node_modules/@lit-protocol/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.js
./node_modules/@lit-protocol/lit-node-client-nodejs/src/index.js
./node_modules/@lit-protocol/lit-node-client/src/index.js
./adapters/litProtocol/hooks/useLitProtocol.tsx
```

**Comment by math77** [comment]
I am seeing this issue in my nextjs app with lit-sdk version 2.1.123

Any tips on how I can solve it?

**Comment by mattcasey** [comment]
@math77 we are just sticking with the original SDK, "lit-js-sdk" for now, so I don't have any suggestions, sorry.

**Comment by DorianWilhelm** [comment]
We are also running into the same issue when trying to upgrade. Downgrading isn't a solution as it's requesting the missing @web3modal/standalone, which then gives us a missing "react-native" dependency.
Any other workarounds available for now?

**Comment by Ansonhkg** [comment]
@DorianWilhelm @mattcasey

Apologies for the delay. I've tested the latest version and it appears to be working. Could you both please try version 2.1.156 and let me know how it works for you?

**Comment by math77** [comment]
@Ansonhkg it seems to be working now, at least I didn't get errors when running the app as I got before. I will do a complete test trying to use the sdk

**Comment by DorianWilhelm** [comment]
@Ansonhkg updating to 2.1.158 works for me 👍
