### ISSUE TITLE
Request for SPA-Friendly OAuth Redirection Mechanism in lit-auth-client

### ISSUE THREAD

**Issue by zach-is-my-name** [LIT-Protocol/js-sdk#268]
#### Issue Description:
I am currently using  `@lit-protocol/lit-auth-client@cayenne` in a Single Page Application (SPA) built with React and React Router. I've noticed that the OAuth flow, particularly when using the `GoogleProvider`, causes a full page refresh during the redirection process. This behavior leads to the loss of in-memory state in my React application, which is not ideal for SPA architecture.

#### Technical Details:
The issue specifically arises in the `signIn` method within `GoogleProvider.js`, where `window.location.assign` is used for redirecting to the Google login page. Additionally, the `authenticate` method uses `window.location.href.startsWith(this.redirectUri)` to handle the callback from Google. These methods result in a full browser reload, which is contrary to the typical behavior in SPAs where navigation is handled by client-side routing without causing page reloads.

#### Suggested Enhancement:
I would like to request an enhancement in how the library handles OAuth redirects. Ideally, the redirection mechanism should be compatible with SPA norms, possibly by leveraging client-side routing methods that do not cause a full page reload. This change would significantly improve the user experience in SPAs and maintain the application state seamlessly through the authentication process.

#### Potential Solutions:
1. Implement a redirection mechanism that integrates with client-side routing libraries like React Router.
2. Provide a configuration option that allows developers to handle the redirection in a SPA-friendly manner.

#### Impact:
This enhancement would greatly benefit developers building SPAs with React (or similar frameworks) by aligning the OAuth flow with the core principles of SPAs. It would maintain the user experience continuity and state persistence across the authentication process.

#### Additional Context:
Here are some relevant snippets from the library where the full page refresh occurs:
- `GoogleProvider.js`:
  - `signIn` method: `window.location.assign(loginUrl);`
  - `authenticate` method: `window.location.href.startsWith(this.redirectUri);`

Thank you for considering this request. I believe this enhancement will make the `@lit-protocol/lit-auth-client` library even more versatile and suitable for modern web application development.

**Comment by Ansonhkg** [comment]
@zach-is-my-name 

Hello Zach! Thanks for the issue! 

Would it help if we instead provide an callback option for the `signIn` and `authenticate` functions so that you can manage the `loginUrl` and `redirectUri` yourself?

**Comment by zach-is-my-name** [comment]
Hi Anson!
Yes, that would be a good solution.

**Comment by Ansonhkg** [comment]
hey @zach-is-my-name let me know if the above PR works for you

**Comment by zach-is-my-name** [comment]
Yes, that worked for me.  Thanks a bunch 😊

**Comment by joshLong145** [comment]
Thanks for the nice breakdown. We have merged support for configurable callback urls #269 will be in the next release build
