### ISSUE TITLE
Feature: Allow options for configuring pkp wallet singing implementation

### ISSUE THREAD

**Issue by joshLong145** [LIT-Protocol/js-sdk#27]
Currently the implementation of `https://github.com/LIT-Protocol/pkp-ethers` does not allow for the `lit action` facilitating singing for the pkp wallet to be configured. Configuration of the options passed to `executeJS` should be possible to allow more sophisticated pkp relationships to be supported.

**Comment by Ansonhkg** [comment]
Hey @joshLong145, you can extend our PKPWallet class to add more custom configurations like this repo:
https://github.com/LIT-Protocol/lit-pkp-sdk/blob/main/src/index.js

Would it help?

**Comment by joshLong145** [comment]
> Hey @joshLong145, you can extend our PKPWallet class to add more custom configurations like this repo: https://github.com/LIT-Protocol/lit-pkp-sdk/blob/main/src/index.js
> 
> Would it help?

this is essentially what we have done to create custom implementations the pop's signing mechanism. but it would be nice if configuration options where added to the `props`

**Comment by Ansonhkg** [comment]
great! i'll add that to my to-do

**Comment by Ansonhkg** [comment]
Hey @joshLong145 we've added pkp-ethers to this repo now you can install it via:

```
yarn add @lit-protocol/pkp-ethers
```

You can now edit your lit action code via the constructor eg:

```
    const pkpWallet = new PKPWallet({
      pkpPubKey: PKP_PUBKEY,
      controllerAuthSig: CONTROLLER_AUTHSIG,
      provider: "https://rpc-mumbai.maticvigil.com",
      debug: true,
      litActionCode: `
      (async () => {
        console.log("Testing");
      })();
      `,
    });

```

Let me know if this work for you?

**Comment by joshLong145** [comment]
> Hey @joshLong145 we've added pkp-ethers to this repo now you can install it via:
> 
> ```
> yarn add @lit-protocol/pkp-ethers
> ```
> 
> You can now edit your lit action code via the constructor eg:
> 
> ```js
>   const pkpWallet = new PKPWallet({
>     pkpPubKey: PKP_PUBKEY,
>     controllerAuthSig: CONTROLLER_AUTHSIG,
>     provider: "https://rpc-mumbai.maticvigil.com",
>     debug: true,
>     litActionCode: `
>     (async () => {
>       console.log("Testing");
>     })();
>     `,
>   });
> ```
> 
> Let me know if this work for you?

Would it also be possible to add `ipfsId` and `jsParams` to the `PKPWallet` props? this would allow for usage of registered `cids` and to pass arbitrary parameters to action implementations. this would then mean you can define either `litActionCode` or `ipfsId` making both optional props. if none are provided then perhaps defaulting to the implementation you have outlined above.

**Comment by Ansonhkg** [comment]
Sure. Let me know if the following works for you:

```
yarn add @lit-protocol/pkp-ethers@2.1.53
```

```js
const pkpWallet = new PKPWallet({
  pkpPubKey: PKP_PUBKEY,
  controllerAuthSig: CONTROLLER_AUTHSIG,
  provider: "https://rpc-mumbai.maticvigil.com",
  debug: true,

  // litActionIPFS: "QmRwN9GKHvCn4Vk7biqtr6adjXMs7PzzYPCzNCRjPFiDjm",
  litActionCode: `
  (async () => {
    const sigShare = await LitActions.signEcdsa({ toSign, publicKey, sigName });
    console.log("extraParams:", extraParams);
  })();
  `,
  litActionJsParams: {
    // this will override the default toSign param
    // toSign: [1, 2, 3, 4, 5],

    // extraParams
    extraParams: [1, 23],
  },
});
```
