### ISSUE TITLE
Breaks at decrypt - parsing SIWE message

### ISSUE THREAD

**Issue by aymenx17** [LIT-Protocol/js-sdk#296]
**It breaks here at decrypt:** 
`	try {
		decryptedString = await LitJsSdk.decryptToString(
			{
				authSig,
				accessControlConditions,
				ciphertext,
				dataToEncryptHash,
				chain: "ethereum",
			},
			litNodeClient,
		);
	} catch (e) {
		console.log(e);
	}`

**With error:**

[Lit-JS-SDK v3.0.27] [ERROR] [core] [id: 168cd37033d2a] Something went wrong, internal id for request: lit_168cd37033d2a. Please provide this identifier with any support requests. Error is Error parsing SIWE message - validation error: SIWE validation failed: parser error: Session key expiration time is not set,Session key expiration time is not set

[Lit-JS-SDK v3.0.27] [ERROR] [core] [id: 168cd37033d2a] most common error: {"errorKind":"Parser","errorCode":"NodeSIWEMessageError","status":400,"message":"Error parsing SIWE message","correlationId":"lit_168cd37033d2a","details":["validation error: SIWE validation failed: parser error: Session key expiration time is not set","Session key expiration time is not set"]}

**Comment by Ansonhkg** [comment]
Hey @aymenx17 sorry for the late reply. Is this still the case? would you be able to create a repo for me to re-produce this error? :)

**Comment by robyn3choi** [comment]
you night have to add `expirationTime` in your `SiweMessage` arguments:
`const msg = new SiweMessage({... expirationTime: [some future Date]})`
