### ISSUE TITLE
Yarn Upgrade Needed

### ISSUE THREAD

**Issue by robertjchristian** [LIT-Protocol/js-sdk#330]
Just a heads up, I required a `yarn upgrade` in order to install.  I'm happy to put in a pull request if desired.

**Comment by Ansonhkg** [comment]
Hey @robertjchristian thanks for reporting it the issue, but i'm failing to re-produce it. What's your yarn & SDK version? have you also tried installing via our `@beta` tag? `yarn add @lit-protocol/lit-node-client@beta`.

Feel free to open a PR though! :)

**Comment by robertjchristian** [comment]
My bad.  I should have captured that.  I will use the beta tag next time, and let you know if I see this again.

**Comment by Ansonhkg** [comment]
@robertjchristian Hey actually we have just made version `3.x.x` as default now! so you can now install it without `beta` tag https://github.com/LIT-Protocol/js-sdk/pull/344

**Comment by joshLong145** [comment]
Closing as issue was determined to be incorrect tag when installing.
