### ISSUE TITLE
Cayenne is evaluating Sepolia access conditions based on data from the Ethereum mainnet.

### ISSUE THREAD

**Issue by henrywfyeung** [LIT-Protocol/js-sdk#392]
**Before reporting, I have already *** 
- checked LIT Protocol [developer docs](https://developer.litprotocol.com/) and/or the [lit-js-sdk](https://lit-protocol.github.io/lit-js-sdk/api_docs_html/).
- searched for other [open issues](https://github.com/LIT-Protocol/lit-js-sdk/issues).

**Describe the bug**
I am using the encryptString and decryptToString functions with unified access conditions for handling token-gated access to information. I did my testing on the Sepolia Testnet (chain ID: 11155111). However, I keep receiving errors indicating 

"Invalid name: please ensure the contract and method you're calling exist! failed to decode empty bytes. if you're using jsonrpc this is likely due to jsonrpc returning `0x` in case contract or method don't exist"

I tried switching my testing to the contracts deployed on Ethereum mainnet, and the error disappeared. I went further to run the test on the same Ethereum contract "0xD4416b13d2b3a9aBae7AcD5D6C2BbDBE25686401", while specifying the chain as Sepolia, and surprisingly the condition evaluation is working. Please see the unified access condition I used for verifying the Ethereum contract's condition on Sepolia network.

`{
        conditionType: "evmContract",
        contractAddress: '0xD4416b13d2b3a9aBae7AcD5D6C2BbDBE25686401',
        functionName: "balanceOf",
        functionParams: [':userAddress', '1234'],
        functionAbi: {
          type: "function",
          stateMutability: "view",
          outputs: [
            {
              type: "uint256",
              name: "",
              internalType: "uint256",
            },
          ],
          name: "balanceOf",
          inputs: [
            {
              type: "address",
              name: "account",
              internalType: "address",
            },
            {
              type: "uint256",
              name: "id",
              internalType: "uint256",
            },
          ],
        },
        chain: 'sepolia',
        returnValueTest: {
          key: "",
          comparator: '>',
          value: '0',
        },
      }`

This indicates that the Sepolia chain access conditions are evaluated based on the data from the Ethereum mainnet. I went down to the SDK code and the error seems to be coming from the Node instead of the client code.

**To Reproduce**
Please use the above unified access condition for encrypting and decrypting strings. Note that the contractAddress points to a contract on Ethereum.

**Expected behavior**
The above condition should evaluated to some meaningful result, while any contracts deployed on Sepolia should throw errors.

**Environment:**
 - Lit SDK version 3.2.2 for nodejs, on the "cayenne" network
 - Node version 18

**Comment by henrywfyeung** [comment]
This issue has been solved by the Lit Protocol team

**Comment by ashikbro019016-lgtm** [comment]
0xc1db4c7c7e8ab3d6168faddb93b2fb79627cf431

Ethereum
