### ISSUE TITLE
[Team Name] <title-for-the-issue>

### ISSUE THREAD

**Issue by gilbert** [LIT-Protocol/js-sdk#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK version

3.0.32, but issue exists on master

### Lit Network

N/A, trying to bundle package for browser

### Description of the bug/issue

```
Can't find variable: global
../../node_modules/@lit-protocol/auth-browser/src/lib/chains/eth.js
```

which points to [this line](https://github.com/LIT-Protocol/js-sdk/blob/7ec1caa8f2a69a851d3346463d72f1702549d0e6/packages/auth-browser/src/lib/chains/eth.ts#L45-L46)

### Severity of the bug

Can't bundle for browser in a create-react-app

### Steps To Reproduce

Using `globalThis` instead of `global` fixes the problem. The rest of the file also uses globalThis, so this would maintain consistency.

**Comment by joshLong145** [comment]
thanks for calling this out! Nice find.

**Comment by gilbert** [comment]
FYI the issue isn't fixed yet. The error was that `global` is not defined. The change in the PR...

```diff
- if (typeof global.Buffer === 'undefined') {
+ if (global && typeof global.Buffer === 'undefined') {
```

...still attempts to use the `global` variable, which will still produce the error.

The solution is to replace all usage of `global` with `globalThis`. The [MDN article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#description) describes why you only need `globalThis`:

> Unlike similar properties such as `window` and `self` [and `global`], `globalThis` is guaranteed to work in window and non-window contexts. In this way, you can access the global object in a consistent manner without having to know which environment the code is being run in.
