### ISSUE TITLE
Getting Timeout error from Lit Node Client while generating sessions

### ISSUE THREAD

**Issue by aditya172926** [LIT-Protocol/js-sdk#462]
### Description of the issue

We are using lit node client from `@lit-protocol/lit-node-client` to generate session sigs using the function `getSessionSigs()` providing its params. Now we are getting an error response from the function with the Timeout message.

System config
Node JS version : 20.11.1
Lit Node Client version: 5.0.0
ethers version: 6.12.0

Network being used: Habanero

### Additional context

Here is the function code using which we are trying to generate Session Sigs.
We are calling the `getSessionSigs` and the `delegateCredits` is called inside it to delegate credits to the signing pkp.

We are using `ethers v6`, and the Lit Node Client uses ethers v5. So instead of calling the capacity delegation logic from the `litNodeClient`, we have modified the logic of `delegateCredits` to work with ethers v6, which was giving me the session sigs.

```
async getSessionSigs(
    authMethod: AuthMethod,
    publicKey: string,
    chainId: number,
    expiration: Date,
  ): Promise<SessionSig> {
    await this.litNodeClient.connect();
    const resourceAbilities = [
      {
        resource: new LitActionResource('*'),
        ability: LitAbility.PKPSigning,
      },
    ];

    const sessionKeyPair = this.litNodeClient.getSessionKey();

    const capacityDelegationAuthSig = await this.delegateCredits(
      [computeAddress(publicKey)],
      chainId,
      expiration,
    );
    this.logger.log('Capacity delegation authsig ', capacityDelegationAuthSig);

    const authNeededCallback = async (
      params: AuthCallbackParams,
    ): Promise<AuthSig> => {
      const response = await this.litNodeClient.signSessionKey({
        sessionKey: sessionKeyPair,
        statement: params.statement,
        authMethods: [authMethod],
        pkpPublicKey: publicKey,
        expiration: params.expiration,
        resources: params.resources,
        chainId: chainId,
      });
      return response.authSig;
    };

    const sessionSigs = await this.litNodeClient
      .getSessionSigs({
        chain: ChainId[chainId],
        expiration: expiration.toISOString(),
        resourceAbilityRequests: resourceAbilities,
        sessionKey: sessionKeyPair,
        authNeededCallback,
        capacityDelegationAuthSig: capacityDelegationAuthSig,
      })
      .catch((err) => {
        this.logger.error(
          'error while attempting to access session signatures: ',
          err,
        );
        throw new ServiceError(
          'Error while attempting to access session signatures',
          err,
        );
      });
    const authSig = sessionSigs[Object.keys(sessionSigs)[0]];
    this.logger.log('authSig ', authSig);
    return authSig;
  }
```

```
  async delegateCredits(
    delegateeAddresses: string[],
    chainId: number,
    expiration: Date,
  ): Promise<AuthSig> {
    const _dappOwnerWalletAddress = await this.controllerWallet.getAddress();
    const _domain = 'example.com';
    const _expiration = expiration.toISOString();
    const _statement = '';
    const _uses = '1';
    const litResource = new LitRLIResource(LIT_CREDITS_TOKENID);
    const recapObject =
      await this.litNodeClient.generateSessionCapabilityObjectWithWildcards([
        litResource,
      ]);
    const capabilities = {
      ...(LIT_CREDITS_TOKENID ? { nft_id: [LIT_CREDITS_TOKENID] } : {}),
      ...(delegateeAddresses
        ? {
            delegate_to: delegateeAddresses.map((address) =>
              address.startsWith('0x') ? address.slice(2) : address,
            ),
          }
        : {}),
      uses: _uses.toString(),
    };

    recapObject.addCapabilityForResource(
      litResource,
      LitAbility.RateLimitIncreaseAuth,
      capabilities,
    );
    const verified = recapObject.verifyCapabilitiesForResource(
      litResource,
      LitAbility.RateLimitIncreaseAuth,
    );
    if (!verified) {
      throw new Error('Failed to verify capabilities for resource');
    }

    const nonce = await this.litNodeClient.getLatestBlockhash();
    let siweMessage = new siwe.SiweMessage({
      domain: _domain,
      address: _dappOwnerWalletAddress,
      statement: _statement,
      uri: SIWE_DELEGATION_URI,
      version: '1',
      chainId: chainId,
      nonce: nonce?.toString(),
      expirationTime: _expiration,
    });
    siweMessage = recapObject.addToSiweMessage(siweMessage);
    const messageToSign = siweMessage.prepareMessage();

    let signature = await this.controllerWallet.signMessage(messageToSign);
    signature = signature.replace('0x', '');
    const authSig = {
      sig: signature,
      derivedVia: 'web3.eth.personal.sign',
      signedMessage: messageToSign,
      address: _dappOwnerWalletAddress.replace('0x', '').toLowerCase(),
      algo: null,
    };
    return authSig;
  }
```

![image](https://github.com/LIT-Protocol/js-sdk/assets/54861484/c703c61f-6940-4bcd-aa14-066e47041aab)

**Comment by zach-is-my-name** [comment]
https://github.com/LIT-Protocol/Issues-and-Reports/issues/34

**Comment by aditya172926** [comment]
I have updated the issue description with the code where we are facing this Timeout issue.

**Comment by aditya172926** [comment]
> Yo. Check this out. Might get you unblocked. [LIT-Protocol/Issues-and-Reports#34](https://github.com/LIT-Protocol/Issues-and-Reports/issues/34)

I confirmed with your thread @zach-is-my-name . I am using the correct  RPC endpoint for the habanero network and initialization of the lit node client in my environment.
The above code was working fine before yesterday without any change.

**Comment by zach-is-my-name** [comment]
Indeed.  A relay mismatch was initially flagged as a potential cause for my issue but aligning the networks did not help my case either.  May I make a suggestion? If you repost your issue here: https://github.com/LIT-Protocol/Issues-and-Reports the entire Lit Team receives it through their Linear (task managment) tracker.  This issue will likely be ignored in this repo as the other ones here are.  Also tag \@glitch003 if you do re-post in that repo.   He is the Founder/CTO and maintains the Node network code

**Comment by aditya172926** [comment]
> Indeed @aditya172926. A relay mismatch was initially flagged as a potential cause for my issue but aligning the networks did not solve the network timeout for me either. May I make a suggestion? If you repost your issue here: https://github.com/LIT-Protocol/Issues-and-Reports the entire Lit Team receives it through their Linear (task managment) tracker. This issue will likely be ignored in this repo as the other ones here are. Also tag @glitch003 if you do re-post in that repo. He is the Founder/CTO and maintains the Node network code

Will do that.

**Comment by joshLong145** [comment]
@aditya172926
It looks like there was an issue signing your session. This is not an issue with the SDK but our network.

**Comment by aditya172926** [comment]
> @aditya172926 It looks like there was an issue signing your session. This is not an issue with the SDK but our network.

I will shift the issue here https://github.com/LIT-Protocol/Issues-and-Reports and close this one.

**Comment by aditya172926** [comment]
Looks like @zach-is-my-name you have already opened the issue with the same problem as mine. So I'll just tag along with that issue https://github.com/LIT-Protocol/Issues-and-Reports/issues/34.

And following your recent thread Removing either litNodeClient or relayURL from litAuthClient works. 

But I'll do some more tests before concluding this fix. But looks like from the comment by @joshLong145 that relayURL will not be required in v5.0.1 sdk

Closing this issue for now. will ping on the existing issue 34 if I get any issue updates on this.

**Comment by aditya172926** [comment]
The bug still persists.
