### ISSUE TITLE
[Closing soon] Lit SDK is unable to regenerate the signature when the stored signature is expired 

### ISSUE THREAD

**Issue by tonyfung99** [LIT-Protocol/js-sdk#90]
**Describe the bug**
Lit SDK cannot regenerate the signature when the stored signature is expired. 
When the user contains an expired signature in local storage and calls `LitJsSdk.checkAndSignAuthMessage`, it is unable to regenerate a new signature and the following actions will be failed.

**To Reproduce**
1. Calls LitJsSdk.checkAndSignAuthMessage with or without an expiration time (the expiration time is not working)
2. Wait until the signature expired 
3. Calls LitJsSdk.checkAndSignAuthMessage again
4. Errors occur

**Expected behavior**
The user should be prompted to sign again after the signature is expired. 

**Screenshots**
![Screenshot 2023-04-28 at 4 19 16 PM](https://user-images.githubusercontent.com/2355642/235094448-2339a26b-b268-4f86-a912-597932907b78.png)

**Environment:**
 - Lit SDK version: `"@lit-protocol/lit-node-client-nodejs@2.1.114"` 
 - Framework: `React`

**Additional info**
In the function `LitJsSdk.checkAndSignAuthMessage`, the parameter `expiration` is ignored.

**Comment by Ansonhkg** [comment]
hey i think this is a bug, we will fix this asap!

**Comment by tonyfung99** [comment]
> hey i think this is a bug, we will fix this asap!

Taking a look into the code base as well, what's the difference between lit-siwe & siwe, why need to fork it?

**Comment by Ansonhkg** [comment]
@tonyfung99 
The original SIWE package includes the entire ethers project, which is quite large. This fork modifies the package to include only the necessary parts of ethers, significantly reducing its size.

**Comment by Ansonhkg** [comment]
@tonyfung99 

Hey just published!

Let me know if this version works for you `2.1.158`
