### ISSUE TITLE
[Closing soon] encrypt-decrypt-react-demo failing.

### ISSUE THREAD

**Issue by JEndler** [LIT-Protocol/js-sdk#94]
Hi there,

First of all, thanks for maintaining such a great project 🚀 
I'm trying to take my first steps, and wanted to try out the encrypt-decrypt-react-demo as a starting point.

I actually tried this example project first https://github.com/debbly/IPFS-lit, but that failed due to some outdated dependencies.

**Before reporting, I have already**
- checked LIT Protocol [developer docs](https://developer.litprotocol.com/) and/or the [lit-js-sdk](https://lit-protocol.github.io/lit-js-sdk/api_docs_html/).
- searched for other [open issues](https://github.com/LIT-Protocol/lit-js-sdk/issues).

**Describe the bug**

I'm running the "encrypt-decrypt-react"-demo, from [here](https://github.com/LIT-Protocol/js-sdk/tree/master/apps/demo-encrypt-decrypt-react).
After installing and running the demo, i'm hitting this error when clicking the "Encrypt & Decrypt String"-Button:

```
caught (in promise) TypeError: this.signer.request is not a function
    at m.request (tslib.es6.js:218:1)
    at Web3Provider.jsonRpcFetchFunc (web3-provider.ts:96:1)
    at Web3Provider.send (web3-provider.ts:167:1)
    at Web3Provider.listAccounts (json-rpc-provider.ts:497:1)
    at connectWeb3 (eth.ts:381:1)
    at async checkAndSignEVMAuthMessage (eth.ts:456:1)
    at async App.js:122:1
    at async benchmark (utils.js:3:1)
    at async go (App.js:121:1)
```

**To Reproduce**
1. Clone this repo
2. cd to /apps/demo-encrypt-decrypt-react
3. npm i
4. npm start
5. Click "Encypt & Decrypt String"
6. Error appears in browser console.

**Expected behavior**
I was expecting some soft of Wallet-Login to pop up.
Judging by the logs, the app connects to the lit-network just fine, and fails afterwards.

**Comment by Ansonhkg** [comment]
Hey, we're planning to remove the ./apps folder from this repository and create a separate repo dedicated to all our demo applications. In the meantime, you can check out https://demo.getlit.dev/simple-encrypt-decrypt for a live demo. There's also a code example provided alongside it, let me know if this is helpful for you?

**Comment by JEndler** [comment]
Thanks a bunch :)
I'm on vacation without my Laptop for the next couple of days, once I have access to a computer again I'll go ahead and test it out.
I'd also be happy to add a readme on how do deploy, or maybe even add a Dockerfile for easy deployment.
